[general]
live_config_reload = true

[window]
opacity = 0.7
padding = { x = 10, y = 10 }
decorations = "Buttonless"
startup_mode = "Maximized"

[font]
normal = { family = "PlemolJP35 Console NF", style = "SemiBold" }
size = 16
